site :opscode
cookbook 'selinux'
cookbook 'ntp'
cookbook 'ruby_build'
cookbook 'rbenv', github: "fnichol/chef-rbenv"
cookbook 'git'
cookbook 'vim'
cookbook 'tmux'
cookbook 'nginx'
cookbook 'users'
cookbook 'sudo'
cookbook 'yum'
cookbook 'mysql'
cookbook 'database'
cookbook 'jenkins'
